### ISSUE TITLE
Logging fails on macOS if log file does not yet exist

### ISSUE THREAD

**Issue by clelange** [rkdarst/prompt-log#3]
If the log file does not yet exist, in both bash and zsh on macOS, logging goes into the void, giving errors after each command entered:

```
~ ❯ source bin/prompt-log.sh
~ ❯ prompt-log demos.out
logging to
~% echo "Hello"
preexec: no such file or directory:
Hello
```

**Comment by MatiasJJ** [comment]
I had this issue today too
